releases:
- name: dynatrace-oneagent
  version: 0.3.1

addons:
- name: dynatrace-oneagent-addon
  jobs:
  - name: dynatrace-oneagent
    release: dynatrace-oneagent
  include:
    deployments: [cf-2ee3c0b0b26eef65fa27]
    stemcell:
      - os: ubuntu-trusty
  properties:
    dynatrace:
      environmentid: rru41549
      apitoken: Jv0PA69ST_qTVqjcwCzWK
      starthelper: 1
#      apiurl: https://abc12345.sprint.dynatracelabs.com/api

- name: dynatrace-oneagent-windows-addon
  jobs:
  - name: dynatrace-oneagent-windows
    release: dynatrace-oneagent
  include:
    deployments: [p-windows-runtime-61e6fb98699283559aa3]
    stemcell:
      - os: windows2012R2
  properties:
    dynatrace:
      environmentid: rru41549
      apitoken: Jv0PA69ST_qTVqjcwCzWK
#      apiurl: https://abc12345.sprint.dynatracelabs.com/api
